[build]
  command = "npm install && npm run build"
  functions = "dist/handlers"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/webhook/job"
  to = "/.netlify/functions/jobWebhook"
  status = 200

[[redirects]]
  from = "/webhook/location"
  to = "/.netlify/functions/locationWebhook"
  status = 200

[[redirects]]
  from = "/location/:jobId"
  to = "/.netlify/functions/queryLocation?jobId=:jobId"
  status = 200