// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Shipment Tracker API",
    "version": "1"
  },
  "paths": {
    "/webhook/job": {
      "post": {
        "summary": "Create a new brokerage job",
        "description": "Webhook endpoint for Cargowise to notify about new jobs",
        "operationId": "jobWebhook.post./webhook/job",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/JobWebhookRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Job created successfully",
            "schema": {
              "$ref": "#/definitions/JobWebhookResponse"
            }
          },
          "400": {
            "description": "Validation error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "409": {
            "description": "Conflict - Job already exists or shipment already associated",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/webhook/location": {
      "post": {
        "summary": "Update shipment location and status",
        "description": "Webhook endpoint for Project44 to send location updates and status",
        "operationId": "locationWebhook.post./webhook/location",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LocationWebhookRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Location updated and status successfully",
            "schema": {
              "$ref": "#/definitions/LocationWebhookResponse"
            }
          },
          "400": {
            "description": "Validation error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "404": {
            "description": "Shipment not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/location/{jobId}": {
      "get": {
        "summary": "Get current location for a job",
        "description": "Query the current location of a shipment by job ID",
        "operationId": "queryLocation.get./location/{jobId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "jobId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Location retrieved successfully",
            "schema": {
              "$ref": "#/definitions/QueryLocationResponse"
            }
          },
          "404": {
            "description": "Job not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "JobWebhookRequest": {
      "properties": {
        "job": {
          "title": "JobWebhookRequest.job",
          "description": "Job identifier",
          "examples": "\"B00001234\"",
          "type": "string"
        },
        "shipment": {
          "title": "JobWebhookRequest.shipment",
          "description": "Shipment number",
          "examples": "\"ABCD12345678\"",
          "type": "string"
        },
        "status": {
          "enum": [
            "ADDED",
            "IN_TRANSIT",
            "DELIVERED",
            "CANCELLED"
          ],
          "title": "JobWebhookRequest.status",
          "description": "Status",
          "examples": "\"ADDED\"",
          "type": "string"
        }
      },
      "required": [
        "job",
        "shipment",
        "status"
      ],
      "additionalProperties": false,
      "title": "JobWebhookRequest",
      "type": "object"
    },
    "LocationWebhookRequest": {
      "properties": {
        "shipment": {
          "title": "LocationWebhookRequest.shipment",
          "description": "Shipment number",
          "examples": "\"ABCD12345678\"",
          "type": "string"
        },
        "latitude": {
          "title": "LocationWebhookRequest.latitude",
          "description": "Latitude",
          "examples": "\"49.0041951\"",
          "type": "string"
        },
        "longitude": {
          "title": "LocationWebhookRequest.longitude",
          "description": "Longitude",
          "examples": "\"-122.7322901\"",
          "type": "string"
        },
        "status": {
          "enum": [
            "ADDED",
            "IN_TRANSIT",
            "DELIVERED",
            "CANCELLED"
          ],
          "title": "LocationWebhookRequest.status",
          "description": "Optional status update",
          "examples": "\"IN_TRANSIT\"",
          "type": "string"
        }
      },
      "required": [
        "shipment",
        "latitude",
        "longitude"
      ],
      "additionalProperties": false,
      "title": "LocationWebhookRequest",
      "type": "object"
    },
    "JobWebhookResponse": {
      "properties": {
        "message": {
          "title": "JobWebhookResponse.message",
          "type": "string"
        },
        "data": {
          "properties": {
            "jobId": {
              "title": "JobWebhookResponse.data.jobId",
              "type": "string"
            },
            "shipmentId": {
              "title": "JobWebhookResponse.data.shipmentId",
              "type": "string"
            },
            "status": {
              "title": "JobWebhookResponse.data.status",
              "type": "string"
            },
            "createdAt": {
              "title": "JobWebhookResponse.data.createdAt",
              "type": "string"
            },
            "updatedAt": {
              "title": "JobWebhookResponse.data.updatedAt",
              "type": "string"
            }
          },
          "required": [
            "jobId",
            "shipmentId",
            "status",
            "createdAt",
            "updatedAt"
          ],
          "additionalProperties": false,
          "title": "JobWebhookResponse.data",
          "type": "object"
        }
      },
      "required": [
        "message",
        "data"
      ],
      "additionalProperties": false,
      "title": "JobWebhookResponse",
      "type": "object"
    },
    "LocationWebhookResponse": {
      "properties": {
        "message": {
          "title": "LocationWebhookResponse.message",
          "type": "string"
        },
        "data": {
          "properties": {
            "shipmentId": {
              "title": "LocationWebhookResponse.data.shipmentId",
              "type": "string"
            },
            "jobId": {
              "title": "LocationWebhookResponse.data.jobId",
              "type": "string"
            },
            "location": {
              "properties": {
                "latitude": {
                  "title": "LocationWebhookResponse.data.location.latitude",
                  "type": "string"
                },
                "longitude": {
                  "title": "LocationWebhookResponse.data.location.longitude",
                  "type": "string"
                }
              },
              "required": [
                "latitude",
                "longitude"
              ],
              "additionalProperties": false,
              "title": "LocationWebhookResponse.data.location",
              "type": "object"
            },
            "createdAt": {
              "title": "LocationWebhookResponse.data.createdAt",
              "type": "string"
            },
            "updatedAt": {
              "title": "LocationWebhookResponse.data.updatedAt",
              "type": "string"
            }
          },
          "required": [
            "shipmentId",
            "jobId",
            "location",
            "createdAt",
            "updatedAt"
          ],
          "additionalProperties": false,
          "title": "LocationWebhookResponse.data",
          "type": "object"
        }
      },
      "required": [
        "message",
        "data"
      ],
      "additionalProperties": false,
      "title": "LocationWebhookResponse",
      "type": "object"
    },
    "QueryLocationResponse": {
      "properties": {
        "job": {
          "title": "QueryLocationResponse.job",
          "description": "Job identifier",
          "examples": "\"B00001234\"",
          "type": "string"
        },
        "shipment": {
          "title": "QueryLocationResponse.shipment",
          "description": "Shipment number",
          "examples": "\"ABCD12345678\"",
          "type": "string"
        },
        "status": {
          "enum": [
            "ADDED",
            "IN_TRANSIT",
            "DELIVERED",
            "CANCELLED"
          ],
          "title": "QueryLocationResponse.status",
          "description": "Status",
          "examples": "\"ADDED\"",
          "type": "string"
        },
        "latitude": {
          "title": "QueryLocationResponse.latitude",
          "description": "Latitude (optional - only if location has been set)",
          "examples": "\"49.0041951\"",
          "type": "string"
        },
        "longitude": {
          "title": "QueryLocationResponse.longitude",
          "description": "Longitude (optional - only if location has been set)",
          "examples": "\"-122.7322901\"",
          "type": "string"
        },
        "createdAt": {
          "title": "QueryLocationResponse.createdAt",
          "description": "Creation timestamp",
          "type": "string"
        },
        "updatedAt": {
          "title": "QueryLocationResponse.updatedAt",
          "description": "Last update timestamp",
          "type": "string"
        }
      },
      "required": [
        "job",
        "shipment",
        "status",
        "createdAt",
        "updatedAt"
      ],
      "additionalProperties": false,
      "title": "QueryLocationResponse",
      "type": "object"
    },
    "ErrorResponse": {
      "properties": {
        "error": {
          "title": "ErrorResponse.error",
          "type": "string"
        },
        "details": {
          "items": {
            "title": "ErrorResponse.details.[]",
            "type": "string"
          },
          "title": "ErrorResponse.details",
          "type": "array"
        }
      },
      "required": [
        "error"
      ],
      "additionalProperties": false,
      "title": "ErrorResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/",
  "schemes": [
    "http",
    "https"
  ]
};